### ISSUE TITLE
[Request for Feedback] Adding an automated test suite to the repo

### ISSUE THREAD

**Issue by onno-vos-dev** [ept/hermitage#17]
At Klarna, we've made extensive use of the scenarios described in this repo on various database engines listed in this repo, so first off thank you for this repo! 🙇 

## Request for Feedback 
The README of this repo states:
> This could probably be automated, but it's actually quite interesting to go through the exercise of stepping through transactions one line at a time, and watching how the database responds.

And I fully agree that it is quite interesting to go through the exercise of stepping through transactions one line at a time. 

We have an internal repository that runs through the scenario's in an automated fashion and tests the correctness. Currently this internal repo implements various Postgres isolation levels but it should be fairly trivial to support other database engines.

I believe there could be a value in adding automated tests to ensure that new DB engines or new versions of existing DB engines continue to pass the tests outlined in this repo. 

Would there be an interest from you @ept and the community to include an automated version of the scenario's? ❓ If so, I'd like to dedicate time to contribute the automated tests as part of this repo. 👍 

## Short description of the automated setup
Due to the ease of implement concurrent processes in Erlang, the repo is written in Erlang and uses JSON files which specifies the scenario's listed in this repo. Adding support for other database engines would not require Erlang expertise but only requires adding a JSON file that describes the scenarios.

It executes the setup described in for example: [postgres.md](https://github.com/ept/hermitage/blob/master/postgres.md) and runs through the various test cases by sending the statements to separate processes in the same fashion as the manual tests would be executed. 

All scenarios described as part of this repo are tested and it asserts the outcome of each statement as well as an end-result that tests  the final outcome of each test. 

Here you can see an example of such output:
**Postgres SERIALIZABLE**
![Screenshot 2024-10-09 at 10 39 54](https://github.com/user-attachments/assets/8b3205c4-7eaf-49ec-a671-5fb6719bbeee)

## Goal
Add a docker-compose setup which runs through the scenario's in an automated fashion without the need to install Erlang, Postgres or any of the other dependencies locally.

**Comment by ept** [comment]
Hi @onno-vos-dev, thanks for getting in touch. Rather than doing all of this in my repo, I think it would be better if you do this in your own repo, and then we can add a link to your repo to the README of this one. That way you can do whatever you like without me having to review things.

**Comment by onno-vos-dev** [comment]
Hi @ept Thank you for getting back to me so quickly! Sounds very reasonable to me 👍 I'll close this issue then and simply open a PR with the additional link in the README once we have the repo in place 👍
